### PR TITLE
Added adjectives

### PR DESCRIPTION
**Pull request by m-r-j**
at LondonR github workshop

### CODE REVIEW

**Comment by gaborcsardi** [comment]
I am not sure if these are positive adjectives. Can you show me a link that they are?

**Comment by m-r-j** [comment]
http://www.oxforddictionaries.com/definition/english/spiffing
http://www.dictionary.com/browse/splendiferous

**Comment by gaborcsardi** [comment]
:) Great, thanks much!

**Comment by gaborcsardi** [comment]
I'll have to merge this by hand because it has conflicts.

**Pull request merged**
